version: '3.8'

services:
  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ez-forum-api
    restart: always
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
      - HOST=0.0.0.0
      - DATABASE_URL=mongodb://mongo:27017/ez-forum
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - OSS_BUCKET=${OSS_BUCKET}
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    depends_on:
      - mongo
    command: sh -c "tsx prisma/seed.ts"  # 启动时运行种子脚本
    networks:
      - ez-forum-network

  # MongoDB服务
  mongo:
    image: mongo:latest
    container_name: ez-forum-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=ez-forum

volumes:
  mongo-data:

networks:
  ez-forum-network:
    driver: bridge
