version: '3.8'

services:
  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ez-forum-api
    restart: always
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
      - HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - OSS_BUCKET=${OSS_BUCKET}
      - OSS_REGION=${OSS_REGION}
      - OSS_EXPIRES_IN=${OSS_EXPIRES_IN}
      - COS_SECRET_ID=${COS_SECRET_ID}
      - COS_SECRET_KEY=${COS_SECRET_KEY}
      - COS_BUCKET=${COS_BUCKET}
      - COS_REGION=${COS_REGION}
      - COS_EXPIRES_IN=${COS_EXPIRES_IN}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    depends_on:
      - mongo
    networks:
      - ez-forum-network

  # MongoDB 服务
  mongo:
    image: mongo:latest
    container_name: ez-forum-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=ez-forum
    networks:
      - ez-forum-network

volumes:
  mongo-data:

networks:
  ez-forum-network:
    driver: bridge