version: '3.8'

services:
  # 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ez-forum-api
    restart: always
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
      - HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
      - OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
      - OSS_BUCKET=${OSS_BUCKET}
      - OSS_REGION=${OSS_REGION}
      - OSS_EXPIRES_IN=${OSS_EXPIRES_IN}
      - COS_SECRET_ID=${COS_SECRET_ID}
      - COS_SECRET_KEY=${COS_SECRET_KEY}
      - COS_BUCKET=${COS_BUCKET}
      - COS_REGION=${COS_REGION}
      - COS_EXPIRES_IN=${COS_EXPIRES_IN}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public
    depends_on:
      - mongo
    networks:
      - ez-forum-network

  # MongoDB 服务 - 配置为副本集模式
  mongo:
    image: mongo:latest
    container_name: ez-forum-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=ez-forum
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/mongodb-keyfile"]
    networks:
      - ez-forum-network
    user: "999:999"

  # MongoDB 副本集初始化服务
  mongo-init:
    image: mongo:latest
    restart: "no"
    depends_on:
      - mongo
    command: >
      bash -c "sleep 10 && mongosh --host mongo:27017 -u $${MONGO_USERNAME} -p $${MONGO_PASSWORD} --authenticationDatabase admin --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})'"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    networks:
      - ez-forum-network

  # 生成MongoDB密钥文件的服务
  mongo-keyfile-generator:
    image: mongo:latest
    restart: "no"
    volumes:
      - ./mongo-keyfile:/mongo-keyfile
    command: >
      bash -c "openssl rand -base64 756 > /mongo-keyfile/mongodb-keyfile && chmod 400 /mongo-keyfile/mongodb-keyfile && chown 999:999 /mongo-keyfile/mongodb-keyfile"
    user: "root"
    
  # 种子数据服务
  seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ez-forum-seed
    restart: "no"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: ["sh", "-c", "sleep 20 && node dist/seed.js"]
    depends_on:
      - app
      - mongo
      - mongo-init
    networks:
      - ez-forum-network

volumes:
  mongo-data:

networks:
  ez-forum-network:
    driver: bridge